version: '3.8'
services:
  client:
    build: 
      context: ./client
      dockerfile: Dockerfile.prod
    restart: unless-stopped
  api:
    build: 
      context: ./api
      dockerfile: Dockerfile.prod
    environment:
      - HOSTNAME=groupomania.site
    restart: unless-stopped
  reverse-proxy:
    build: 
      context: ./reverse-proxy
      dockerfile: Dockerfile.prod
    ports:
      - 80:80
    restart: unless-stopped
    depends_on:
      - api
      - client
