version: '3.8'
services:
  api:
    build: 
      context: ./api
      dockerfile: Dockerfile.dev
    volumes:
      - type: bind
        source: ./api
        target: /app
      - type: volume
        target: /app/node_modules
    ports:
      - 5000:80